### ISSUE TITLE
question about the evaluation.

### ISSUE THREAD

**Issue by minimini-1** [chandagrover/sem-cs#2]
Hello I have a question about the evaluation.

In the paper, you compared CLIPStyler and Gen-Art with DISTS and NIMA indicators,
but could you tell me which image and which style text you used?

Thank you.

**Comment by chandagrover** [comment]
Hi,

We reported DISTS and NIME scores of 100 images and style texts and not of a single image in the paper.

Thanks.

**Comment by minimini-1** [comment]
Hi thanks for the reply.

I'd like to conduct an evaluation using the same image and text data, could you share to me?

Thanks.
